### PR TITLE
Implement `heroku addons --all`

### PR DESCRIPTION
**Pull request by bjeanes**
Partially addresses #10 too

``` sh-session
$ heroku addons [-a bjeanes] # inferred if in app directory
=== bjeanes Add-on Resources
heroku-postgresql:dev    @budding-busily-2230     DATABASE, HEROKU_POSTGRESQL_VIOLET
newrelic:stark           @newrelic-8895216        NEWRELIC
pgbackups:plus           @pgbackups-8071074       PGBACKUPS

$ heroku addons --all
=== Add-on Resources
deployhooks:hipchat               @deployhooks-hipchat-9703260  support-api                  DEPLOYHOOKS_HIPCHAT
deployhooks:hipchat               @deployhooks-hipchat-9852225  addons-staging               DEPLOYHOOKS_HIPCHAT
deployhooks:http                  @deployhooks-http-8635555     addons-staging               DEPLOYHOOKS_HTTP
deployhooks:http                  @deployhooks-http-9511216     dashboard-next               DEPLOYHOOKS_HTTP
heroku-postgresql:basic           @unwinding-busily-7091        webcolours                   DATABASE, WEBCOLOUR_DB on webcolour-reporter
heroku-postgresql:dev             @budding-busily-2230          bjeanes                      DATABASE, HEROKU_POSTGRESQL_VIOLET
heroku-postgresql:dev             @dreaming-merrily-3553        grabshot                     DATABASE
[... omitted ...]
papertrail:fredrik                @papertrail-9673756           dashboard-next               PAPERTRAIL
pgbackups:auto-month              @pgbackups-9702935            support-api                  PGBACKUPS
rediscloud:500                    @rediscloud-10103133          support-api                  REDISCLOUD
redistogo:medium                  @singing-tidily-5337          agile-refuge-6412            REDISTOGO
redistogo:nano                    @redistogo-6556590            shatei                       REDISTOGO
redistogo:nano                    @redistogo-8746670            shatei-bo                    REDISTOGO
securekey:fortnightly             @securekey-5396795            addons-staging               SECUREKEY
sendgrid:starter                  @sendgrid-9840547             ion-bo                       SENDGRID
```

And, drawing attention to the following snippet in particular, it shows that I've added a `on <app name>` when the attachment is to a foreign app:

```
heroku-postgresql:basic           @unwinding-busily-7091        webcolours                   DATABASE, WEBCOLOUR_DB on webcolour-reporter
```

cc @heroku/add-ons

### CODE REVIEW

**Comment by bjeanes** [comment]
I wonder if I should do `other-app::ATTACHMENT_NAME` instead of `ATTACHMENT_NAME on other-app`. This might be more consistent with other attachment references.

**Comment by mathias** [comment]
This looks good as far as code. Digging the `display_attachments` lambda in there since a first instinct in Ruby would probably be something like a method that takes both the addon and the list of `attachments_by_resource` -- this shows it doesn't need to.

We should open a task / card to add a test for this new behavior to the Direwolf suite, as well.

**Comment by mnoble** [comment]
I don't know if we should be including attached-app information in the `heroku addons` command; seems out of place. That should be left up to `addons:attachments`.

As far as attachments go, there's two main questions people have when invoking attachment commands. 1) What's attached to my app and 2) Where are my resources attached to?

1 is covered by `addons:attachments` already.

I think we should add a flag to handle number 2. Something like `addons:attachments --resource @slowly-walking-1234`. It'd display the outbound attachments of that resource and the apps they're going to.

**Comment by mathias** [comment]
Should this be a command like `heroku addons:attachments --all` instead? The `heroku addons` list has changed to include billing app, config vars, and service+plan since this was started, I think. Listing all attachments with their billing resources under a `heroku addons:attachments --all` command seems to make sense to fill in more global information. If I was looking for all of my resources and where they're attached, I'll want some command -- the other option, as @mnoble indicated, is knowing (in the case of #10) that I have a resource with attachments and I can't find the attachments, is to make a `heroku addons:attachments --resource @resource-name-123` command to show only that resource's attachments. Could we do both, eventually?

**Comment by bjeanes** [comment]
I think we definitely want all of: `heroku addons:attachments {[--app my-app],--resource @my-resource,--all}`. I still think we want `heroku addons --all` because sometimes you want to see everything even when you have an implicit `--app` scope, I just don't think it needs to include attached info. Maybe we are saying the same thing?

**Comment by bjeanes** [comment]
What if we dropped `heroku addons:attachments` and just had `heroku addons {[--app my-app],--resource @my-resource,--all}` which displayed both resources and attachments (in two separate tables):

**Scoped to app:**

```sh-session
$ heroku addons [--app this-app] # implicitly scoped if in app repo
== Add-ons owned by this-app
Plan                     Add-on                   Price
------------------------ ------------------------ --------------
heroku-postgresql:dev    @budding-busily-2230     free
newrelic:stark           @newrelic-8895216        $1/month
pgbackups:plus           @pgbackups-8071074       free

== Add-ons attached to this-app
Attachment Name         Add-on Name              Service               Billing App
----------------------- ------------------------ --------------------- ----------------
DATABASE                @budding-busily-2230     heroku-postgresql     this-app
HEROKU_POSTGRES_TEAL    @budding-busily-2230     heroku-postgresql     this-app
NEW_RELIC               @newrelic-8895216        newrelic              this-app
PGBACKUPS               @pgbackups-8071074       pgbackups             this-app
REDIS                   @gently-flowing-1252     openredis             a-different-app
```

**Scoped to resource:**

```sh-session
$ heroku addons --resource @gently-flowing-1252
== Info
Name:          gently-flowing-1252
Plan:          heroku-postgresql:dev
Price:         free
Billing App:   this-app

== Attachments
Attachment Name         Attached App
----------------------- ------------
DATABASE                this-app    
HEROKU_POSTGRES_TEAL    this-app
CUSTOMER_DB             other-app
```

**Unscoped:**

```sh-session
$ heroku addons [--all] # implicitly all if not in app repo
== Add-ons
Plan                     Add-on                  Billing App        Price     
------------------------ ----------------------- ------------------ ------------
heroku-postgresql:dev    @budding-busily-2230    this-app           free      
newrelic:stark           @newrelic-8895216       this-app           $1/month
pgbackups:plus           @pgbackups-8071074      this-app           free
openredis:micro          @gently-flowing-1252    a-different-app    $10/month

To view attachments, run `heroku addons --resource SOME_RESOURCE_NAME`.
```

Thoughts?

**Comment by mattreduce** [comment]
@heroku/add-ons check out Bo's [most recent comment](https://github.com/heroku/heroku-addon-attachments/pull/32#issuecomment-85860618) here. He and I discussed this last night, but we wanted to hear what ya'll think, as well.

**Comment by mattreduce** [comment]
@bjeanes 

>What if we dropped heroku addons:attachments and just had heroku addons {[--app my-app],--resource @my-resource,--all} which displayed both resources and attachments

I like it :+1: was hoping for others to chime in here, but perhaps we should just move forward with this UX for now

**Comment by bjeanes** [comment]
OK I implemented approximately my proposal above and pushed the latest here.

Actual output from using the commands:

``` sh-session
$ heroku addons --resource practicing-nobly-1495
=== Info
Name:        practicing-nobly-1495
Plan:        heroku-postgresql:premium-yanari
Billing App: addons-reports
Price:       $200.00/month

=== Attachments
App             Name
--------------  ------------------------
addons          ADDONS_REPORTS
addons-reports  DATABASE
addons-reports  HEROKU_POSTGRESQL_SILVER

$ heroku addons --app addons-reports
=== Add-on Resources for addons-reports
Plan                              Name                   Price
--------------------------------  ---------------------  -------------
heroku-postgresql:premium-yanari  practicing-nobly-1495  $200.00/month
openredis:micro                   swimming-truly-2371    $10.00/month
pgbackups:plus                    shining-calmly-9125    free

=== Add-on Attachments for addons-reports
Name                      Add-on                 Billing App
------------------------  ---------------------  --------------
ADDONS_DATABASE           writing-aptly-5837     addons
DATABASE                  practicing-nobly-1495  addons-reports
HEROKU_POSTGRESQL_SILVER  practicing-nobly-1495  addons-reports
OPENREDIS                 swimming-truly-2371    addons-reports
PGBACKUPS                 shining-calmly-9125    addons-reports
VAULT_USAGE               resting-keenly-2521    vault-usage
```

I won't post a `heroku addons --all` because it's a big list, but it works basically the same as `--app` except the tables include some extra columns.

You can pass any one of `--all`, `--app A`, or `--resource R`. `--all` is the default outside of an app directory, and `--app A` is the default inside an app directory.

Please play around with this and leave any suggestions here. I've also removed the `addons:attachments` command.

**Comment by mattreduce** [comment]
@bjeanes thanks! Giving this a try now

**Comment by mattreduce** [comment]
I love it! :boom:

**Comment by bjeanes** [comment]
@mattreduce excellent!

**Pull request closed without merging**
